import SwiftUI
import Translation

struct SentenceMeaningView: View {
    @Environment(\.dismiss) private var dismiss
    let text: String
    let phrase: Phrase
    var expressionMeaning: String? = nil

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: Spacing.lg) {
                    PhraseExampleText(text: text, phrase: phrase).textSelection(.enabled)
                        .accessibilityIdentifier("meaningSourceSentence")
                    if let authored = phrase.exampleTranslations?[text] {
                        Text("Japanese translation").font(.headline)
                        Text(authored).font(Typography.meaning).textSelection(.enabled)
                            .accessibilityIdentifier("sentenceTranslation")
                    } else if #available(iOS 18.0, *) {
                        JapaneseSentenceTranslation(text: text).id(text)
                    } else if #available(iOS 17.4, *) {
                        SystemSentenceTranslation(text: text)
                    } else {
                        Text("Select the English sentence above and choose Translate from the menu. Choose Japanese as the translation language.")
                            .foregroundStyle(Palette.secondary)
                    }
                    Divider()
                    Text("Meaning of the expression").font(.headline)
                    Text(phrase.phrase).font(.title3)
                    Text(expressionMeaning ?? phrase.japanese).foregroundStyle(Palette.secondary)
                    if phrase.exampleTranslations?[text] == nil {
                        Text("Sentence translations are generated by Apple Translate. Use the expression's meaning and context to check idioms and phrasal verbs.")
                            .font(.caption).foregroundStyle(Palette.secondary)
                    }
                }.padding(Spacing.lg).frame(maxWidth: 680, alignment: .leading).frame(maxWidth: .infinity)
            }.background { ReadingBackground() }.foregroundStyle(Palette.ink)
                .navigationTitle("Sentence meaning").navigationBarTitleDisplayMode(.inline)
                .toolbar {
                    ToolbarItem(placement: .confirmationAction) {
                        Button("Done") { dismiss() }.accessibilityIdentifier("closeSentenceMeaning")
                    }
                }
        }.tint(Palette.ink)
    }
}

@available(iOS 17.4, *)
private struct SystemSentenceTranslation: View {
    let text: String
    @State private var presented = false
    var body: some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            Button("Translate sentence", systemImage: "translate") { presented = true }.frame(minHeight: 44)
            Text("Choose Japanese in the translation window. The first translation may require a language download.")
                .font(.subheadline).foregroundStyle(Palette.secondary)
        }.translationPresentation(isPresented: $presented, text: text)
    }
}

@available(iOS 18.0, *)
private struct JapaneseSentenceTranslation: View {
    let text: String
    @State private var configuration: TranslationSession.Configuration?
    @State private var translation: String?
    @State private var isLoading = false
    @State private var failed = false

    var body: some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            Text("Japanese translation").font(.headline)
            if let translation {
                Text(translation).font(Typography.meaning).textSelection(.enabled)
                    .accessibilityIdentifier("sentenceTranslation")
            } else {
                Text("Translate this sentence into Japanese. The first use may ask to download English and Japanese language data; after downloading, translation works on your device.")
                    .font(.subheadline).foregroundStyle(Palette.secondary)
                if failed {
                    Text("Translation couldn't finish. Check that language downloads are allowed and there is enough free space, then try again. You can still read the expression's meaning below.")
                        .font(.subheadline).foregroundStyle(Palette.secondary)
                        .accessibilityIdentifier("sentenceTranslationError")
                }
                if isLoading {
                    ProgressView("Translating…").accessibilityIdentifier("sentenceTranslationLoading")
                } else {
                    Button(failed ? LocalizedStringKey("Try translation again") : LocalizedStringKey("Show Japanese translation"), systemImage: "translate") {
                        failed = false
                        isLoading = true
                        if configuration != nil { configuration?.invalidate() }
                        else if #available(iOS 26.4, *) {
                            configuration = .init(source: .init(identifier: "en"), target: .init(identifier: "ja"), preferredStrategy: .highFidelity)
                        } else {
                            configuration = .init(source: .init(identifier: "en"), target: .init(identifier: "ja"))
                        }
                    }.frame(minHeight: 44).accessibilityIdentifier("translateSentence")
                }
            }
        }.translationTask(configuration, action: translate)
    }

    // Keep the non-Sendable session entirely on its task executor. Only the
    // resulting String crosses to MainActor for display.
    nonisolated private func translate(using session: TranslationSession) async {
        do {
            try await session.prepareTranslation()
            let response = try await session.translate(text)
            guard !Task.isCancelled else { return }
            await MainActor.run {
                translation = response.targetText
                isLoading = false
            }
        } catch {
            guard !Task.isCancelled else { return }
            await MainActor.run {
                failed = true
                isLoading = false
            }
        }
    }
}
