"""Original plain-English explanations of the single sense taught in each lesson."""
meanings = {
    'bring up': 'Start talking about a topic.',
    'get across': 'Explain something so another person understands it.',
    'follow up': 'Do something more after an earlier talk or action.',
    'push back': 'Say that you disagree with an idea or request.',
    'talk through': 'Talk about each part of something to understand it.',
    'wrap up': 'Finish something, such as a meeting or a task.',
    'catch up': 'Talk about what has happened since you last met.',
    'open up': 'Start talking honestly about your feelings.',
    'reach out': 'Contact someone to talk, help, or ask for help.',
    'drift apart': 'Slowly become less close to each other.',
    'let down': 'Make someone unhappy by not doing what they trusted you to do.',
    'bring out': 'Make a part of someone’s character easier to see.',
    'put off': 'Decide to do something later.',
    'work out': 'End well or happen in a good way.',
    'fall through': 'Not happen, even though it was planned.',
    'turn down': 'Say no to an offer, invitation, or request.',
    'come up': 'Happen without warning and need your attention.',
    'rule out': 'Decide that something is not possible or will not be chosen.',
    'come across': 'Seem a certain way to other people.',
    'figure out': 'Find an answer or understand something by thinking.',
    'back up': 'Show facts or examples that support what someone says.',
    'go over': 'Read, check, or discuss something carefully, often again.',
    'think through': 'Think carefully about what might happen because of a decision.',
    'point out': 'Tell someone about a fact or detail they may not have noticed.',
    'look for': 'Try to find someone or something.',
    'look into': 'Try to learn more about a problem or idea.',
    'look after': 'Keep someone or something safe and well.',
    'look up': 'Find a fact or meaning in a book or online.',
    'look forward to': 'Feel happy about something that will happen.',
    'look out for': 'Watch carefully so you notice someone or something.',
    'look up to': 'Respect someone and think they are a good example.',
    'look back on': 'Think about something that happened in the past.',
    'look through': 'Check or read the things inside something.',
    'look down on': 'Think that someone or something is less important or good than you.',
    'get back to': 'Contact someone again to give an answer or more information.',
    'get around to': 'Finally do something you have been too busy to do.',
    'get along with': 'Like someone and have a friendly relationship with them.',
    'get over': 'Feel better after an illness or a difficult experience.',
    'get through': 'Finish a lot of work or things you need to do.',
    'get away with': 'Do something wrong without being punished or getting into trouble.',
    'get by': 'Have just enough money or skill to manage your life or a task.',
    'take on': 'Agree to do a job or be responsible for something.',
    'take over': 'Start doing a job or being in charge instead of someone else.',
    'take in': 'Understand new information.',
    'take up': 'Start doing something regularly, such as a hobby.',
    'take back': 'Say that something you said earlier was wrong or unfair.',
    'take off': 'Leave the ground and start flying.',
    'put up with': 'Accept something unpleasant and keep living or working with it.',
    'put forward': 'Suggest an idea for people to think about.',
    'put together': 'Make something by joining or organizing its parts.',
    'put aside': 'Stop thinking about a worry or disagreement for a while.',
    'put down': 'Say something that makes someone feel stupid or unimportant.',
    'put through': 'Connect a phone call so someone can speak to another person.',
    'come up with': 'Think of an idea or an answer.',
    'come around': 'Change your mind and begin to agree.',
    'come down to': 'Depend mainly on one thing.',
    'come along': 'Go somewhere with someone.',
    'go through': 'Check or discuss every part of something.',
    'go ahead': 'Start or continue doing something you planned.',
    'go along with': 'Agree with a plan and support it.',
    'bring about': 'Make something happen or change.',
    'bring back': 'Make someone remember something from the past.',
    'bring in': 'Ask someone to join and help with a job.',
    'bring forward': 'Change the time of an event so it happens earlier.',
    'turn up': 'Arrive or appear, sometimes when nobody expects you.',
    'turn out': 'Have a result or be a certain way, as you discover later.',
    'turn to': 'Go to a person or use something when you need help.',
    'turn around': 'Make a bad situation become better.',
    'give up': 'Stop trying to do something.',
    'give in': 'Finally agree to something you did not want to accept.',
    'give away': 'Tell someone a secret, sometimes without meaning to.',
    'set up': 'Plan or prepare something so it can happen.',
    'set aside': 'Keep some time or money for a particular use.',
    'set out': 'Explain a plan or idea clearly and in order.',
    'run into': 'Meet someone when you did not expect to.',
    'run out of': 'Have none of something left because it has all been used.',
    'run by': 'Tell someone an idea and ask what they think.',
    'hold off': 'Wait before doing something.',
    'hold up': 'Make someone or something late.',
    'hold on': 'Wait for a moment.',
}
